version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feed_data_processor_app
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      DB_HOST: ${MYSQL_DB_HOST}
      DB_NAME: ${MYSQL_DB_NAME}
      DB_USER: ${MYSQL_DB_USER}
      DB_PASSWORD: ${MYSQL_DB_PASSWORD}
    networks:
      - app-network
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    container_name: feed_data_processor_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: feed_data_processor_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PGSQL_DB_NAME}
      POSTGRES_USER: ${PGSQL_DB_USER}
      POSTGRES_PASSWORD: ${PGSQL_DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
